### ISSUE TITLE
Import fails

### ISSUE THREAD

**Issue by kradonneoh** [lucidrains/flash-cosine-sim-attention#6]
Something seems to have changed overnight -- I'm getting an error when running `import flash_cosine_sim_attention` (running off `0.1.15` pip-installed):

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flash_cosine_sim_attention/__init__.py", line 1, in <module>
    from flash_cosine_sim_attention.flash_cosine_sim_attention import flash_cosine_sim_attention, plain_cosine_sim_attention, l2norm_tensors
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flash_cosine_sim_attention/flash_cosine_sim_attention.py", line 10, in <module>
    exec(open('flash_cosine_sim_attention/version.py').read())
FileNotFoundError: [Errno 2] No such file or directory: 'flash_cosine_sim_attention/version.py'
```

When the package is `make install`'d, everything works as expected (I'm assuming it's another bundling issue :^))

**Comment by lucidrains** [comment]
@kradonneoh https://github.com/lucidrains/flash-cosine-sim-attention/commit/178c41a797d4a5389728a80cad505d899edc211f may be fixed in 0.1.17 :crossed_fingers:

**Comment by lucidrains** [comment]
@kradonneoh do let me know if the kernel works or does not work for your problem 🙏
